### ISSUE TITLE
ffdecsawrapper crashing

### ISSUE THREAD

**Issue by lucky79** [bas-t/dvbloopback#2] opened 2015-10-01 08:05 UTC
Hello,

I am getting quite frequent segfaults (once a day or so) of ffdecsawrapper followed by bunch of dvblb_fake_ioctl interrupted: errors.
Compiled from dvbloopback repo with opensource TBS drivers on debian jessie stock kernel 3.16.0-4-amd64, using your configure script.

Any ideas what can be causing this?

[283741.436216] ffdecsawrapper[25303]: segfault at 7fdc4b391000 ip 000000000046b9b2 sp 00007fdc4b38ea70 error 4 in ffdecsawrapper[400000+de000]
[283742.655062] dvblb_fake_ioctl interrupted: 2150133582
[283743.655858] dvblb_fake_ioctl interrupted: 28483

**Comment by bas-t** [comment] 2015-10-01 12:23
If you recompile the stock kernel, you should be running 3.16.0-900-amd64.
The kernel you are running has no patched dvb-core module.

**Comment by lucky79** [comment] 2015-10-01 13:25
Many thanks for your reply and sorry for maybe stupid questions. Your configure script did not recompile the kernel but only tbs v4l drivers, which seems to have dvb-core patched. I though the dvbloopback module would not work at all without the patch (locking when accessing the virtual dvb adapter or not loading etc.), its working fine instead, mythtv too... just having this occasional crash problem. Do I need to recompile the stock kernel to solve this?

**Comment by bas-t** [comment] 2015-10-01 13:34
So I guess you did './configure --v4l=yes' right?
If so, my advise is to just run './configure' but make sure you comment out the backports lines in your sources.list while doing this.
The v4l method is just there for debugging purposes. It should work, though. I'll have a look, maybe the patch is outdated again

**Comment by bas-t** [comment] 2015-10-01 14:59
The patch is not outdated, so I don't have a clue as to what went wrong on your system.
The segfault messages, and especially the dvbl_fake_ioctl messages point in the direction that the dvb-core module is not patched ok. Or you have several versions, etc.

My script is ment to either recompile a Debian stock kernel, or pick a vanilla one. I strongly advise against the v4l option, unless you are willing to accept and debug a broken system.

BTW: "./configure --vanilla=3.10.90" is one of my personal favorites. It's rockstable.

**Comment by bas-t** [comment] 2015-10-01 15:32
Oh, I see I did not answer your question (well implicit I did)
Yes, to solve this, either recompile your stock kernel or compile a vanilla one.

Just so we are clear:
for the stock option: comment out the backports lines (if you have them) in your sources.list, do apt-get update and then, in the root dir of your dvbloopback clone, run './configure', or if you need the kernel's headers installed, run './configure --headers=yes'.

For the vanilla option: run './configure --vanilla=somekernel'. Since you need the opensource TBS drivers, you can choose to replace somekernel by either a 3.10.x or a 4.1.x or a 4.2.x or a 4.3-rcx kernel series.
Then accept the supplied kernel config and you should be good running ffdecsawrapper without troubles.

In all cases: before you start, delete /usr/bin/ffdecsawrapper, just to make sure it is compiled ok.
And last but not least: make sure your system is fully updated.

**Comment by bas-t** [comment] 2015-10-01 16:29
I may have missed something, do you need to compile Luis Alves' repo?

I wish you'd inform me on what led to your troubles anyway (sigh).
It seems to me that your effort on how to resolve your problems are next to none.
So now I have to guess...

**Comment by lucky79** [comment] 2015-10-01 21:22
Sorry I was away from the pc for some time... 

compiled with './configure --v4l=tbs' as I need either Luis Alvez or TBS drivers for my 6981 card. Luis Alvez seemed to be easier as your configure script supports it out of box and compilation was smooth. Later on I found that the 6981 card might be supported in kernel since 3.16 but did not try yet, everything seemed to be working and then I realized something is wrong after the first segfault. 
Didn't want to break my existing old sasc-ng/mythtv install until I know that new install will work, so tried to compile everything on a VM first, then did the same on the physical box. 
I am really willing to spend time to build stable mythtv system which would work for years like the old system was, with some minor issues but pretty stable. And really appreciate your efforts with further developing and maintaining this piece of software which I thought is dead already :)

Will try to use some of the newer vanilla kernels as you suggest and let you know the results.

Many thanks!

**Comment by bas-t** [comment] 2015-10-02 01:23
OK, so you need TBS 6981. In that case I think you better compile the latest stable vanilla kernel.
(./configure --vanilla=4.2.2)
Luis did not update his repo for quite some time, and while he was updating it there where many issues. So only use this option as a last resort.

**Comment by bas-t** [comment] 2015-10-02 01:40
Come to think of it, you don't need TBS 6281 or TBS 6285 support. So I guess your best bet is running
./configure --vanilla=4.2.2 --drivers=no

**Comment by lucky79** [comment] 2015-10-02 13:20
Ok, if the vanilla 4.2.2 kernel would not work I think I should use the official TBS drivers, which were working fine until now on the old system (using 2.6.38 kernel). I really hope it will work with the vanilla kernel as with the official drivers it would be quite some work :D anyway I'll try and let you know how it went. 
Thanks very much

**Comment by bas-t** [comment] 2015-10-02 13:36
OK. closing this now, as this is not related to either dvbloopback or ffdecsawrapper

**Closed as completed by bas-t** 2015-10-02 13:36 UTC

**Comment by bas-t** [comment] 2015-10-02 13:45
I conducted serious debug tests that show that both dvbloopback and ffdecsawrapper are in good shape.
Just so you know.

**Comment by lucky79** [comment] 2015-10-07 08:46
I am afraid I have bad news. Compiled kernel 4.2.2 as suggested, everything went smoothly but after some time ffdecsawrapper still crashes, exactly as it was with previous 3.16 kernel :( I am starting to think it might be HW issue with the new MB/CPU/RAM I have used for this MythTV backend as getting strange errors before ffdecsawrapper crash:

[147564.836760] cx23885[0]: mpeg risc op code error
[147564.836765] cx23885[0]: TS2 C - dma channel status dump
[147564.836768] cx23885[0]:   cmds: init risc lo   : 0xb1082000
[147564.836770] cx23885[0]:   cmds: init risc hi   : 0x00000000
[147564.836773] cx23885[0]:   cmds: cdt base       : 0x000105e0
[147564.836775] cx23885[0]:   cmds: cdt size       : 0x0000000a
[147564.836778] cx23885[0]:   cmds: iq base        : 0x00010440
[147564.836780] cx23885[0]:   cmds: iq size        : 0x00000010
[147564.836782] cx23885[0]:   cmds: risc pc lo     : 0xb1082004
[147564.836785] cx23885[0]:   cmds: risc pc hi     : 0x00000000
[147564.836787] cx23885[0]:   cmds: iq wr ptr      : 0x00004111
[147564.836789] cx23885[0]:   cmds: iq rd ptr      : 0x00004110
[147564.836792] cx23885[0]:   cmds: cdt current    : 0x000105e8
[147564.836794] cx23885[0]:   cmds: pci target lo  : 0xacd06340
[147564.836796] cx23885[0]:   cmds: pci target hi  : 0x00000000
[147564.836799] cx23885[0]:   cmds: line / byte    : 0x00ac0000
[147564.836801] cx23885[0]:   risc0: 0x1c0002f0 [ write sol eol count=752 ]
[147564.836805] cx23885[0]:   risc1: 0xacd06340 [ readc sol eol 23 22 20 14 13 count=832 ]
[147564.836810] cx23885[0]:   risc2: 0x00000000 [ INVALID count=0 ]
[147564.836814] cx23885[0]:   risc3: 0x1c0002f0 [ write sol eol count=752 ]
[147564.836817] cx23885[0]:   (0x00010440) iq 0: 0x00000000 [ INVALID count=0 ]
[147564.836820] cx23885[0]:   (0x00010444) iq 1: 0x1c0002f0 [ write sol eol count=752 ]
[147564.836823] cx23885[0]:   iq 2: 0xacd06c10 [ arg #1 ]
[147564.836826] cx23885[0]:   iq 3: 0x00000000 [ arg #2 ]
[147564.836828] cx23885[0]:   (0x00010450) iq 4: 0x00000000 [ INVALID count=0 ]
[147564.836831] cx23885[0]:   (0x00010454) iq 5: 0x1c0002f0 [ write sol eol count=752 ]
[147564.836834] cx23885[0]:   iq 6: 0xacd06050 [ arg #1 ]
[147564.836836] cx23885[0]:   iq 7: 0x00000000 [ arg #2 ]
[147564.836838] cx23885[0]:   (0x00010460) iq 8: 0x1c0002f0 [ write sol eol count=752 ]
[147564.836841] cx23885[0]:   iq 9: 0xacd06340 [ arg #1 ]
[147564.836844] cx23885[0]:   iq a: 0x00000000 [ arg #2 ]
[147564.836846] cx23885[0]:   (0x0001046c) iq b: 0x1c0002f0 [ write sol eol count=752 ]
[147564.836849] cx23885[0]:   iq c: 0xacd06630 [ arg #1 ]
[147564.836852] cx23885[0]:   iq d: 0x00000000 [ arg #2 ]
[147564.836854] cx23885[0]:   (0x00010478) iq e: 0x1c0002f0 [ write sol eol count=752 ]
[147564.836857] cx23885[0]:   iq f: 0xacd06920 [ arg #1 ]
[147564.836859] cx23885[0]:   iq 10: 0xa9b97894 [ arg #2 ]
[147564.836860] cx23885[0]: fifo: 0x00006000 -> 0x7000
[147564.836861] cx23885[0]: ctrl: 0x00010440 -> 0x104a0
[147564.836863] cx23885[0]:   ptr1_reg: 0x00006020
[147564.836865] cx23885[0]:   ptr2_reg: 0x000105e8
[147564.836868] cx23885[0]:   cnt1_reg: 0x00000002
[147564.836870] cx23885[0]:   cnt2_reg: 0x00000009
[154577.943646] ffdecsawrapper[1743]: segfault at 7f69775a2000 ip 000000000046b9b2 sp 00007f697759fa70 error 4 in ffdecsawrapper[400000+de000]

Will try to put back the old MB which was working fine for couple of years

**Comment by bas-t** [comment] 2015-10-07 09:12
I've seen quite similar logs, seems to be related to kernel version/hardware not cooperating well.
So I'm curious about what will happen when you reinstall your old mobo.
Mind you, the cx23885 driver is in a less then perfect state.
I've got some minor issues with it (using DVBSky T982), but so far it only eats a couple of extra cpu cycles, so investigating it is not high on my prio list.

**Comment by bas-t** [comment] 2015-10-07 11:44
Just a shot in the dark for you, but it seems to solve my minor problems with the cx23885 driver, it might help you too.
I' ve pushed a possible fix for the ffdecsawrapper segfault (not curing the cx23885 itself of course) to a new branch: test. Do you want to try it?
See: 92325f85b2f6fab8a4778630b023655625899052

**Comment by bas-t** [comment] 2015-10-07 11:48
Oh, forgot: I just compiled 4.2.3 with it from the test branch.  './configure --vanilla=4.2.3'

**Comment by bas-t** [comment] 2015-10-07 13:01
Pushed it to master, deleted test branch.

**Comment by lucky79** [comment] 2015-10-07 14:16
Will give it a shot, thank you :+1: It seems that even the driver is giving these errors, I don't have to reload the modules and restarting ffdecsawrapper only makes mythtv working again. So if it would not crash I would be happy. Anyway will also swap the old MB just to see if the driver will be happy then.

**Comment by lucky79** [comment] 2015-10-07 16:54
After compilation and reboot to new kernel, I am getting dvblb_fake_ioctl interrupted immediately after card is accessed. MythTV starts but there are no channels unfortunately.

**Comment by bas-t** [comment] 2015-10-07 17:15
Does that mean you don't get 'cx23885[0]: mpeg risc op code error' and so on anymore?

**Comment by bas-t** [comment] 2015-10-07 17:17
And what about the segfault?

**Comment by lucky79** [comment] 2015-10-07 17:25
That means it doesnt work at all, I have no channels in mythtv and cant tune to anything. No segfault though... however booting back to the "old" 4.2.2 and all works again

**Comment by bas-t** [comment] 2015-10-07 17:29
I'd still like to see the output from dmesg, starting with 'dvbloopback: registering x adapters' with your newer kernel

**Comment by lucky79** [comment] 2015-10-08 08:19
Sorry for the delay, its a live system so cannot play with it in the evening when my wife wants to watch TV :D Here you go:
[   59.443723] dvbloopback: registering 5 adapters
[   59.443789] DVB: registering new adapter (DVB-LOOPBACK)
[   59.448130] DVB: registering new adapter (DVB-LOOPBACK)
[   59.450601] DVB: registering new adapter (DVB-LOOPBACK)
[   59.451122] DVB: registering new adapter (DVB-LOOPBACK)
[   59.451624] DVB: registering new adapter (DVB-LOOPBACK)
[   81.663715] i2c i2c-11: cx24117_load_firmware: FW version 1.44.95.2
[   81.663723] i2c i2c-11: cx24117_firmware_ondemand: Firmware upload complete
[   84.512232] dvblb_fake_ioctl interrupted: 1074818898

This is how it looks like when its working with the old version:
[  205.491092] dvbloopback: registering 5 adapters
[  205.491156] DVB: registering new adapter (DVB-LOOPBACK)
[  205.495700] DVB: registering new adapter (DVB-LOOPBACK)
[  205.496308] DVB: registering new adapter (DVB-LOOPBACK)
[  205.496870] DVB: registering new adapter (DVB-LOOPBACK)
[  205.497435] DVB: registering new adapter (DVB-LOOPBACK)
[  227.709357] i2c i2c-11: cx24117_load_firmware: FW version 1.44.95.2
[  227.709364] i2c i2c-11: cx24117_firmware_ondemand: Firmware upload complete
[  237.357141] i2c i2c-8: cx24117_load_firmware: FW version 1.44.95.2
[  237.357149] i2c i2c-8: cx24117_firmware_ondemand: Firmware upload complete

**Comment by bas-t** [comment] 2015-10-08 08:48
So mythtv recognizes your tuners but just can't tune to a channel, right?
I have to think about this, since the "((cmd == FE_SET_PROPERTY) || (cmd == FE_GET_PROPERTY))" stuff that is in the abnormal call to usercopy() should imo be somewhere else.
However, you could still be facing a hardware problem.
The thing is, I tested with a regular exported usercopy (in new personal branch) with 5 different kernels and 3 different DVB devices. All of those tests show an improved performance of both mythtv and FFdecsawrapper, albeit they are all DVB-C devices and you use a dish.

**Comment by lucky79** [comment] 2015-10-08 09:48
EDIT: It seems virtual adapters are not created:
root@mythbackend:~# ffdecsawrapper -i
0: STB0899 Multistandard
1: Conexant CX24117/CX24132
2: Conexant CX24117/CX24132
3: Conexant CX24117/CX24132
4: Conexant CX24117/CX24132
root@mythbackend:~#

Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext recorders/dvbchannel.cpp:234 (Open) DVBChan[1](/dev/dvb/adapter9/frontend0): Failed to open DVB frontend device due to fatal error or too many attempts.
Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext recorders/channelbase.cpp:1232 (CreateChannel) ChannelBase: CreateChannel() Error: Failed to open device /dev/dvb/adapter9/frontend0
Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext main_helpers.cpp:199 (setupTVs) Problem with capture cardsCard 1failed init
Oct  8 11:47:15 mythbackend  mythbackend[1866]: W CoreContext recorders/dvbchannel.cpp:229 (Open) DVBChan[3](/dev/dvb/adapter8/frontend0): Opening DVB frontend device failed.
                        eno: Bad address (14)
Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext recorders/dvbchannel.cpp:234 (Open) DVBChan[3](/dev/dvb/adapter8/frontend0): Failed to open DVB frontend device due to fatal error or too many attempts.
Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext recorders/channelbase.cpp:1232 (CreateChannel) ChannelBase: CreateChannel() Error: Failed to open device /dev/dvb/adapter8/frontend0
Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext main_helpers.cpp:199 (setupTVs) Problem with capture cardsCard 3failed init
Oct  8 11:47:15 mythbackend  mythbackend[1866]: W CoreContext recorders/dvbchannel.cpp:229 (Open) DVBChan[5](/dev/dvb/adapter7/frontend0): Opening DVB frontend device failed.
                        eno: Bad address (14)
Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext recorders/dvbchannel.cpp:234 (Open) DVBChan[5](/dev/dvb/adapter7/frontend0): Failed to open DVB frontend device due to fatal error or too many attempts.
Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext recorders/channelbase.cpp:1232 (CreateChannel) ChannelBase: CreateChannel() Error: Failed to open device /dev/dvb/adapter7/frontend0
Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext main_helpers.cpp:199 (setupTVs) Problem with capture cardsCard 5failed init
Oct  8 11:47:15 mythbackend  mythbackend[1866]: W CoreContext recorders/dvbchannel.cpp:229 (Open) DVBChan[7](/dev/dvb/adapter6/frontend0): Opening DVB frontend device failed.
                        eno: Bad address (14)
Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext recorders/dvbchannel.cpp:234 (Open) DVBChan[7](/dev/dvb/adapter6/frontend0): Failed to open DVB frontend device due to fatal error or too many attempts.
Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext recorders/channelbase.cpp:1232 (CreateChannel) ChannelBase: CreateChannel() Error: Failed to open device /dev/dvb/adapter6/frontend0
Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext main_helpers.cpp:199 (setupTVs) Problem with capture cardsCard 7failed init
Oct  8 11:47:15 mythbackend  mythbackend[1866]: W CoreContext recorders/dvbchannel.cpp:229 (Open) DVBChan[9](/dev/dvb/adapter5/frontend0): Opening DVB frontend device failed.
                        eno: Bad address (14)
Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext recorders/dvbchannel.cpp:234 (Open) DVBChan[9](/dev/dvb/adapter5/frontend0): Failed to open DVB frontend device due to fatal error or too many attempts.
Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext recorders/channelbase.cpp:1232 (CreateChannel) ChannelBase: CreateChannel() Error: Failed to open device /dev/dvb/adapter5/frontend0
Oct  8 11:47:15 mythbackend  mythbackend[1866]: E CoreContext main_helpers.cpp:199 (setupTVs) Problem with capture cardsCard 9failed init
Oct  8 11:47:15 mythbackend  mythbackend[1866]: W CoreContext main_helpers.cpp:214 (setupTVs) MythBackend: No valid capture cards are defined in the database.

And here is the ffdecsawrapper log:
Oct  8 11:57:33.949 dvr: Starting thread on /dev/dvb/adapter5/dvr1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:33.949 frontend: Starting thread on /dev/dvb/adapter5/frontend1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:33.949 demux: Starting thread on /dev/dvb/adapter5/demux1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:34.949 frontend: Starting thread on /dev/dvb/adapter6/frontend1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:34.950 demux: Starting thread on /dev/dvb/adapter6/demux1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:34.958 dvr: Starting thread on /dev/dvb/adapter6/dvr1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:35.958 frontend: Starting thread on /dev/dvb/adapter7/frontend1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:35.960 demux: Starting thread on /dev/dvb/adapter7/demux1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:35.970 dvr: Starting thread on /dev/dvb/adapter7/dvr1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:36.971 frontend: Starting thread on /dev/dvb/adapter8/frontend1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:36.971 demux: Starting thread on /dev/dvb/adapter8/demux1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:36.976 dvr: Starting thread on /dev/dvb/adapter8/dvr1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:37.977 frontend: Starting thread on /dev/dvb/adapter9/frontend1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:37.988 dvr: Starting thread on /dev/dvb/adapter9/dvr1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:37.988 demux: Starting thread on /dev/dvb/adapter9/demux1
The thread scheduling parameters indicate:
policy = 0
priority = 0
Oct  8 11:57:37.989 : Listening on port 5456
Oct  8 11:57:44.057 CSA: Got command(9): I idx: 0 pid: 0
Oct  8 11:57:44.113 CSA: Got command(9): I idx: 0 pid: 0
Oct  8 11:57:44.169 CHANNEL: Clearing tuning cache due to switch cmd
Oct  8 11:57:45.299 CHANNEL: Clearing tuning cache due to switch cmd
Oct  8 11:57:45.645 CHANNEL: Clearing tuning cache due to switch cmd
Oct  8 11:57:45.775 CHANNEL: Clearing tuning cache due to switch cmd
Oct  8 11:57:45.825 frontend: Didn't read enough data
Oct  8 11:57:45.938 THREAD: Netwatcher thread ended (pid=1997, tid=0)

I still plan to swap the MB but did not have time yet :( Anyway I dont think this is a HW problem, there might just be some difference between DVB-C and DVB-S devices? I dont understand programming sorry.. But I am happy to help with debugging. I can give you remote access if you want check yourself

**Comment by bas-t** [comment] 2015-10-09 07:37
Sure the difference between DVB-C and DVB-S is big, but that is in this case only interesting where it comes to my attempt to restructure the usercopy() call. It does not relate in any way to the cause of your segfaults, being the misbehaviour of your driver (and/or hardware for that matter), causing the dvbloopback kernel module to print what's going on.
FFdecsawrapper should not segfault in such a case, but also print an error to dmesg and gracefully exit.
Since the effect is the same,  I'm not very interested in addressing the segfault.
As for the attempt to restructure the usercopy() call, I've concluded that it is bases on a thinko, so I reverted that.

**Comment by bas-t** [comment] 2015-10-09 08:33
FYI:
https://github.com/ljalves/linux_media/issues/74
https://github.com/ljalves/linux_media/issues/62

and many more...

I believe a patch for this is on it's way:
https://patchwork.linuxtv.org/patch/31625/

**Comment by bas-t** [comment] 2015-10-09 10:12
Hi,
I added the patch, so we don't have to wait for it. Testing as we speek.
Care to test this too?
Please recompile 4.2.3 with it and let me know if it solves your issue.
(./configure --vanilla=4.2.3 --drivers=no)
If not, I guess you are stuck with official TBS drivers.

**Comment by lucky79** [comment] 2015-10-14 14:42
Hi,
thanks! Compiling now. Will update you shortly

**Comment by lucky79** [comment] 2015-10-14 19:41
I have bad news unfortunately, everything seems to be fine, virtual adapters are created, no errors in dmesg or ffdecsawrapper but mythtv can't tune any channel...

**Comment by lucky79** [comment] 2015-10-15 05:37
Its not only TBS cards related, but also STB0899 (TT-Budget S2-3200 PCI) is affected. So not sure if official TBS drivers will fix my problem with current branch... Will test this as I have seen you have a dvbloopback-tbs version available.
Thanks!

**Comment by lucky79** [comment] 2016-02-18 13:44
Finally I've got some time to recompile with the official tbs drivers using your tbs-dvbloopback repository and have no more crashes so far :) Used stock 3.16 kernel, everything went quick and smooth, dmesg clean, just awesome. Thanks a lot for your great work. I would send you some beers if I know where to! :D
